"
This class offers a number of extra icons that work with the Glamorous Theme.
"
Class {
	#name : #GLMUIThemeExtraIcons,
	#superclass : #Object,
	#classInstVars : [
		'icons'
	],
	#category : #'Glamour-Morphic-Theme'
}

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousAccept [
	^ Smalltalk ui icons iconNamed: #glamorousAccept
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousAdd [
	^ Smalltalk ui icons iconNamed: #glamorousAdd
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousAlarm [
	^ Smalltalk ui icons iconNamed: #glamorousAlarm
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousBookmark [
	^ Smalltalk ui icons iconNamed: #glamorousBookmark
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousBrowse [
	^ Smalltalk ui icons iconNamed: #glamorousBrowse
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousBug [
	^ Smalltalk ui icons iconNamed: #glamorousBug
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousCancel [
	^ Smalltalk ui icons iconNamed: #glamorousCancel
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousClose [
	^ Smalltalk ui icons iconNamed: #glamorousClose
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousDown [
	^ Smalltalk ui icons iconNamed: #glamorousDown
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousDropDown [
	^ Smalltalk ui icons iconNamed: #glamorousDropDown
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousEdit [
	^ Smalltalk ui icons iconNamed: #glamorousEdit
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousExample [
	^ Smalltalk ui icons iconNamed: #glamorousExample
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousFolder [
	^ Smalltalk ui icons iconNamed: #glamorousFolder
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousGo [
	^ Smalltalk ui icons iconNamed: #glamorousGo
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousGrayCircle [
	^ Smalltalk ui icons iconNamed: #glamorousGrayCircle
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousGrayCircleEmpty [
	^ Smalltalk ui icons iconNamed: #glamorousGrayCircleEmpty
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousGreenCircle [
	^ Smalltalk ui icons iconNamed: #glamorousGreenCircle
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousHelp [
	^ Smalltalk ui icons iconNamed: #glamorousHelp
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousInspect [
	^ Smalltalk ui icons iconNamed: #glamorousInspect
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousInto [
	^ Smalltalk ui icons iconNamed: #glamorousInto
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousLargeGrayCircleEmphasized [
	^ Smalltalk ui icons iconNamed: #glamorousLargeGrayCircleEmphasized
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousLeft [
	^ Smalltalk ui icons iconNamed: #glamorousLeft
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousLeftSide [
	^ Smalltalk ui icons iconNamed: #glamorousLeftSide
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousMore [
	^ Smalltalk ui icons iconNamed: #glamorousMore
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousOpen [
	^ Smalltalk ui icons iconNamed: #glamorousOpen
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousOpenFromUrl [
	^ Smalltalk ui icons iconNamed: #glamorousOpenFromUrl
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousOver [
	^ Smalltalk ui icons iconNamed: #glamorousOver
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousPlay [
	^ Smalltalk ui icons iconNamed: #glamorousPlay
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousRedCircle [
	^ Smalltalk ui icons iconNamed: #glamorousRedCircle
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousRedo [
	^ Smalltalk ui icons iconNamed: #glamorousRedo
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousRefresh [
	^ Smalltalk ui icons iconNamed: #glamorousRefresh
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousRemove [
	^ Smalltalk ui icons iconNamed: #glamorousRemove
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousRestart [
	^ Smalltalk ui icons iconNamed: #glamorousRestart
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousRight [
	^ Smalltalk ui icons iconNamed: #glamorousRight
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousRightSide [
	^ Smalltalk ui icons iconNamed: #glamorousRightSide
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousSave [
	^ Smalltalk ui icons iconNamed: #glamorousSave
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousSaveToUrl [
	^ Smalltalk ui icons iconNamed: #glamorousSaveToUrl
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousSearch [
	^ Smalltalk ui icons iconNamed: #glamorousSearch
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousSpawn [
	^ Smalltalk ui icons iconNamed: #glamorousSpawn
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousThrough [
	^ Smalltalk ui icons iconNamed: #glamorousThrough
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousTrash [
	^ Smalltalk ui icons iconNamed: #glamorousTrash
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousUndo [
	^ Smalltalk ui icons iconNamed: #glamorousUndo
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousUp [
	^ Smalltalk ui icons iconNamed: #glamorousUp
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousZoomIn [
	^ Smalltalk ui icons iconNamed: #glamorousZoomIn
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousZoomOut [
	^ Smalltalk ui icons iconNamed: #glamorousZoomOut
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousZoomToFit [
	^ Smalltalk ui icons iconNamed: #glamorousZoomToFit
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamourousNextFailure [
	^ Smalltalk ui icons iconNamed: #glamourousNextFailure
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamourousNextParser [
	^ Smalltalk ui icons iconNamed: #glamourousNextParser
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamourousNextProduction [
	^ Smalltalk ui icons iconNamed: #glamourousNextProduction
]

{ #category : #utils }
GLMUIThemeExtraIcons class >> icons [
	^ icons ifNil: [icons := Dictionary new] 
]

{ #category : #utils }
GLMUIThemeExtraIcons class >> importIcons [
	"self importIcons"
	| wantedIcons |
	self resetIcons.
	wantedIcons := #(
		'glamorousInspect'
		'glamorousExample'
		'glamorousHelp'
		'glamorousSearch'
		'glamorousAccept'
		'glamorousCancel'
		'glamorousBrowse'
		'glamorousAdd'
		'glamorousRemove'
		'glamorousTrash'
		'glamorousUp'
		'glamorousDown'
		'glamorousDropDown'
		'glamorousLeft'
		'glamorousRight'
		'glamorousEdit'
		'glamorousAlarm'
		'glamorousRedCircle'
		'glamorousGreenCircle'
		'glamorousGrayCircle'
		'glamorousGrayCircleEmpty'
		'glamorousLargeGrayCircleEmphasized'
		'glamorousUndo'
		'glamorousRedo'
		'glamorousPlay'
		'glamorousGo'
		'glamorousRestart'
		'glamorousOver'
		'glamorousInto'
		'glamorousThrough'
		'glamorousBookmark'
		'glamorousOpen'
		'glamorousSave'
		'glamorousOpenFromUrl'
		'glamorousSaveToUrl'
		'glamorousFolder'
		'glamorousRefresh'
		'glamorousSpawn'
		'glamorousBug'
		'glamorousLeftSide'
		'glamorousRightSide'
		'glamorousZoomIn'
		'glamorousZoomOut'
		'glamorousZoomToFit'
		'glamorousMore'
		"'glamourousNextParser'
		'glamourousNextProduction'
		'glamourousNextFailure'").
	(Smalltalk at:
	 #MooseScripts) 
		importIcons: wantedIcons 
		fromFolder: 'icons' 
		inClass: self 
		category: 'icons'
]

{ #category : #utils }
GLMUIThemeExtraIcons class >> resetIcons [
	icons := nil
]
