"
This class offers a number of extra icons that work with the Glamorous Theme.
"
Class {
	#name : #GLMUIThemeExtraIcons,
	#superclass : #Object,
	#classInstVars : [
		'icons'
	],
	#category : #'Glamour-Morphic-Theme'
}

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousAccept [
	^ Smalltalk ui icons glamorousAccept
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousAdd [
	^ Smalltalk ui icons glamorousAdd
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousAlarm [
	^ Smalltalk ui icons glamorousAlarm
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousBookmark [
	^ Smalltalk ui icons glamorousBookmark
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousBrowse [
	^ Smalltalk ui icons glamorousBrowse
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousBug [
	^ Smalltalk ui icons glamorousBug
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousCancel [
	^ Smalltalk ui icons glamorousCancel
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousClose [ 
	^ Smalltalk ui icons glamorousClose
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousDown [
	^ Smalltalk ui icons glamorousDown
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousDropDown [
	^ Smalltalk ui icons glamorousDropDown
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousEdit [
	^ Smalltalk ui icons glamorousEdit
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousExample [
	^ Smalltalk ui icons glamorousExample
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousFolder [
	^ Smalltalk ui icons glamorousFolder
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousGo [
	^ Smalltalk ui icons glamorousGo
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousGrayCircle [
	^ Smalltalk ui icons glamorousGrayCircle
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousGrayCircleEmpty [
	^ Smalltalk ui icons glamorousGrayCircleEmpty
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousGreenCircle [
	^ Smalltalk ui icons glamorousGreenCircle
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousHelp [
	^ Smalltalk ui icons glamorousHelp
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousInspect [
	^ Smalltalk ui icons glamorousInspect
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousInto [
	^ Smalltalk ui icons glamorousInto
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousLargeGrayCircleEmphasized [
	^ Smalltalk ui icons glamorousLargeGrayCircleEmphasized
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousLeft [
	^ Smalltalk ui icons glamorousLeft
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousLeftSide [
	^ Smalltalk ui icons glamorousLeftSide
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousMore [
	^ Smalltalk ui icons glamorousMore
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousOpen [
	^ Smalltalk ui icons glamorousOpen
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousOpenFromUrl [
	^ Smalltalk ui icons glamorousOpenFromUrl
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousOver [
	^ Smalltalk ui icons glamorousOver
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousPlay [
	^ Smalltalk ui icons glamorousPlay
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousRedCircle [
	^ Smalltalk ui icons glamorousRedCircle
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousRedo [
	^ Smalltalk ui icons glamorousRedo
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousRefresh [
	^ Smalltalk ui icons glamorousRefresh
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousRemove [
	^ Smalltalk ui icons glamorousRemove
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousRestart [
	^ Smalltalk ui icons glamorousRestart
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousRight [
	^ Smalltalk ui icons glamorousRight
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousRightSide [
	^ Smalltalk ui icons glamorousRightSide
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousSave [
	^ Smalltalk ui icons glamorousSave
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousSaveToUrl [ 
	^ Smalltalk ui icons glamorousSaveToUrl
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousSearch [
	^ Smalltalk ui icons glamorousSearch
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousSpawn [
	^ Smalltalk ui icons glamorousSpawn
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousThrough [
	^ Smalltalk ui icons glamorousThrough
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousTrash [
	^ Smalltalk ui icons glamorousTrash
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousUndo [
	^ Smalltalk ui icons glamorousUndo
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousUp [
	^ Smalltalk ui icons glamorousUp
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousZoomIn [
	^ Smalltalk ui icons glamorousZoomIn
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousZoomOut [
	^ Smalltalk ui icons glamorousZoomOut
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamorousZoomToFit [
	^ Smalltalk ui icons glamorousZoomToFit
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamourousNextFailure [
	^ Smalltalk ui icons glamourousNextFailure
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamourousNextParser [
	^ Smalltalk ui icons glamourousNextParser
]

{ #category : #icons }
GLMUIThemeExtraIcons class >> glamourousNextProduction [
	^ Smalltalk ui icons glamourousNextProduction
]

{ #category : #utils }
GLMUIThemeExtraIcons class >> icons [
	^ icons ifNil: [icons := Dictionary new] 
]

{ #category : #utils }
GLMUIThemeExtraIcons class >> importIcons [
	"self importIcons"
	| wantedIcons |
	self resetIcons.
	wantedIcons := #(
		'glamorousInspect'
		'glamorousExample'
		'glamorousHelp'
		'glamorousSearch'
		'glamorousAccept'
		'glamorousCancel'
		'glamorousBrowse'
		'glamorousAdd'
		'glamorousRemove'
		'glamorousTrash'
		'glamorousUp'
		'glamorousDown'
		'glamorousDropDown'
		'glamorousLeft'
		'glamorousRight'
		'glamorousEdit'
		'glamorousAlarm'
		'glamorousRedCircle'
		'glamorousGreenCircle'
		'glamorousGrayCircle'
		'glamorousGrayCircleEmpty'
		'glamorousLargeGrayCircleEmphasized'
		'glamorousUndo'
		'glamorousRedo'
		'glamorousPlay'
		'glamorousGo'
		'glamorousRestart'
		'glamorousOver'
		'glamorousInto'
		'glamorousThrough'
		'glamorousBookmark'
		'glamorousOpen'
		'glamorousSave'
		'glamorousOpenFromUrl'
		'glamorousSaveToUrl'
		'glamorousFolder'
		'glamorousRefresh'
		'glamorousSpawn'
		'glamorousBug'
		'glamorousLeftSide'
		'glamorousRightSide'
		'glamorousZoomIn'
		'glamorousZoomOut'
		'glamorousZoomToFit'
		'glamorousMore'
		"'glamourousNextParser'
		'glamourousNextProduction'
		'glamourousNextFailure'").
	(Smalltalk at:
	 #MooseScripts) 
		importIcons: wantedIcons 
		fromFolder: 'icons' 
		inClass: self 
		category: 'icons'
]

{ #category : #utils }
GLMUIThemeExtraIcons class >> resetIcons [
	icons := nil
]
