Extension { #name : #UITheme }

{ #category : #'*glamour-morphic-theme' }
UITheme >> configureWatcherWindowLabelAreaFor: aWindow [
	^ self configureWindowLabelAreaFor: aWindow
]

{ #category : #'*glamour-morphic-theme' }
UITheme >> watcherWindowActiveFillStyleFor: aWindow [

	^ self windowActiveFillStyleFor: aWindow
]

{ #category : #'*glamour-morphic-theme' }
UITheme >> watcherWindowInactiveFillStyleFor: aWindow [

	^ self windowInactiveFillStyleFor: aWindow
]
