Class {
	#name : #GLMDashboardExtentStrategy,
	#superclass : #Object,
	#category : #'Glamour-Browsers-Dashboard'
}

{ #category : #'as yet unclassified' }
GLMDashboardExtentStrategy >> initializeContainer: aPanelMorph [
	
	^ self subclassResponsibility 
]

{ #category : #'as yet unclassified' }
GLMDashboardExtentStrategy >> initializeFirstColumn: aPanelMorph [
	
	^ self subclassResponsibility 
]

{ #category : #'as yet unclassified' }
GLMDashboardExtentStrategy >> initializePane: aMorphPane [
	
	^ self subclassResponsibility 
]

{ #category : #'as yet unclassified' }
GLMDashboardExtentStrategy >> initializeSecondColumn: aPanelMorph [
	
	^ self subclassResponsibility 
]
