Extension { #name : #GLMDashboardExtentStrategy }

{ #category : #'*glamour-morphic-renderer' }
GLMDashboardExtentStrategy >> initializeContainer: aPanelMorph [
	
	^ self subclassResponsibility 
]

{ #category : #'*glamour-morphic-renderer' }
GLMDashboardExtentStrategy >> initializeFirstColumn: aPanelMorph [
	
	^ self subclassResponsibility 
]

{ #category : #'*glamour-morphic-renderer' }
GLMDashboardExtentStrategy >> initializePane: aMorphPane [
	
	^ self subclassResponsibility 
]

{ #category : #'*glamour-morphic-renderer' }
GLMDashboardExtentStrategy >> initializeSecondColumn: aPanelMorph [
	
	^ self subclassResponsibility 
]
