"
This class has no implementation. It is only useful for identifying the scroll panes that need to resize the content horizontally (to stretch their size), like in the case of the magritte forms. It is instantiated in the MorhpicRenderer and queried for in the GlamorousSystemWindow.
"
Class {
	#name : #GLMScrollPaneForHResize,
	#superclass : #ScrollPane,
	#category : #'Glamour-Morphic-Renderer'
}
