Class {
	#name : #GLMBrickPopupHelpThemer,
	#superclass : #GLMBrickPopupThemer,
	#category : #'Glamour-Morphic-Brick-Theme'
}

{ #category : #'brick-popup' }
GLMBrickPopupHelpThemer >> backgroundColor [

	^ Color r: 190 g: 236 b: 250 range: 255
]

{ #category : #'brick-popup' }
GLMBrickPopupHelpThemer >> borderColor [

	^ Color r: 48 g:194 b:240 range: 255
]

{ #category : #'brick-popup' }
GLMBrickPopupHelpThemer >> textColor [

	^ Color r: 16 g: 172 b: 221 range: 255
]
