Class {
	#name : #GLMBrickPopupSuccessThemer,
	#superclass : #GLMBrickPopupThemer,
	#category : #'Glamour-Morphic-Brick-Theme'
}

{ #category : #'as yet unclassified' }
GLMBrickPopupSuccessThemer >> backgroundColor [

	^ Color r: 204 g: 229 b: 204 range: 255
]

{ #category : #'as yet unclassified' }
GLMBrickPopupSuccessThemer >> borderColor [
	"#7FBF7F"
	^ Color r: 127 g: 191 b: 127 range: 255
]

{ #category : #'as yet unclassified' }
GLMBrickPopupSuccessThemer >> textColor [
	
	^ Color r: 0 g: 115 b: 0 range: 255
]
