"
asd
a
sd
as
d
asd
"
Trait {
	#name : #GLMBrickScrollbarStyle,
	#category : #'Glamour-Morphic-Brick-Theme'
}

{ #category : #'brick-scrollbar' }
GLMBrickScrollbarStyle >> scrollbarColor [

	^ Color lightGray alpha: 0.5
]

{ #category : #'brick-scrollbar' }
GLMBrickScrollbarStyle >> scrollbarCornerRadius [

	^ 0
]

{ #category : #'brick-scrollbar' }
GLMBrickScrollbarStyle >> scrollbarOffset [

	^ 1
]

{ #category : #'brick-scrollbar' }
GLMBrickScrollbarStyle >> scrollbarPosition [

	^ #right
]

{ #category : #'brick-scrollbar' }
GLMBrickScrollbarStyle >> scrollbarWidth [

	^ 3
]
