Class {
	#name : #GLMBrickWrapper,
	#superclass : #GLMBrickGeneralWrapper,
	#category : #'Glamour-Morphic-Brick-Layouts-Utils'
}

{ #category : #api }
GLMBrickWrapper >> brickBounds: aRectangle [

	^ self brick brickBounds: aRectangle
]

{ #category : #api }
GLMBrickWrapper >> customHeight [

	^ self brick customHeight
]

{ #category : #api }
GLMBrickWrapper >> customWidth [

	^ self brick customWidth
]

{ #category : #api }
GLMBrickWrapper >> extent [

	^ self brick extent
]

{ #category : #api }
GLMBrickWrapper >> floating [

	^ self brick floating
]

{ #category : #api }
GLMBrickWrapper >> hAlign [

	^ self brick hAlign
]

{ #category : #api }
GLMBrickWrapper >> hResizing [

	^ self brick hResizing
]

{ #category : #api }
GLMBrickWrapper >> height [

	^ self brick height
]

{ #category : #api }
GLMBrickWrapper >> innerBounds [

	^ self brick innerBounds
]

{ #category : #api }
GLMBrickWrapper >> invalidateLayout [

	^ self brick invalidateLayout
]

{ #category : #api }
GLMBrickWrapper >> marginBottom [

	^ self brick marginBottom
]

{ #category : #api }
GLMBrickWrapper >> marginLeft [

	^ self brick marginLeft
]

{ #category : #api }
GLMBrickWrapper >> marginRight [

	^ self brick marginRight
]

{ #category : #api }
GLMBrickWrapper >> marginTop [

	^ self brick marginTop
]

{ #category : #api }
GLMBrickWrapper >> onChildrenLayouted [

	^ self brick onChildrenLayouted
]

{ #category : #api }
GLMBrickWrapper >> onLayoutEvent: aLayoutEvent [

	^ self brick onLayoutEvent: aLayoutEvent
]

{ #category : #api }
GLMBrickWrapper >> onLayouted [

	^ self brick onLayouted
]

{ #category : #api }
GLMBrickWrapper >> outerBounds [

	^ self brick outerBounds
]

{ #category : #api }
GLMBrickWrapper >> paddingBottom [

	^ self brick paddingBottom
]

{ #category : #api }
GLMBrickWrapper >> paddingLeft [

	^ self brick paddingLeft
]

{ #category : #api }
GLMBrickWrapper >> paddingRight [

	^ self brick paddingRight
]

{ #category : #api }
GLMBrickWrapper >> paddingTop [

	^ self brick paddingTop
]

{ #category : #api }
GLMBrickWrapper >> translateX: anObject [

	^ self brick translateX: anObject
]

{ #category : #api }
GLMBrickWrapper >> translateY: anObject [

	^ self brick translateY: anObject
]

{ #category : #api }
GLMBrickWrapper >> vAlign [

	^ self brick vAlign
]

{ #category : #api }
GLMBrickWrapper >> vResizing [

	^ self brick vResizing
]

{ #category : #api }
GLMBrickWrapper >> width [

	^ self brick width
]

{ #category : #api }
GLMBrickWrapper >> wrappedBounds [

	^ self brick wrappedBounds
]
