Class {
	#name : #GLMBrickPopupThemer,
	#superclass : #GLMBrickThemerModule,
	#category : #'Glamour-Morphic-Brick-Theme'
}

{ #category : #'brick-popup' }
GLMBrickPopupThemer >> backgroundColor [

	^ Color white
]

{ #category : #'brick-popup' }
GLMBrickPopupThemer >> borderColor [

	^ Color lightGray
]

{ #category : #'brick-popup' }
GLMBrickPopupThemer >> borderWidth [

	^ 1
]

{ #category : #'brick-popup' }
GLMBrickPopupThemer >> textColor [

	^ Color lightGray darker
]
