"
asdasd
"
Class {
	#name : #GLMPhlowrTableColumn,
	#superclass : #Object,
	#instVars : [
		'title',
		'computation',
		'style'
	],
	#category : #'Glamour-Morphic-Brick-Phlowr'
}

{ #category : #accessing }
GLMPhlowrTableColumn >> computation [
	^ computation
]

{ #category : #accessing }
GLMPhlowrTableColumn >> computation: anObject [
	computation := anObject
]

{ #category : #accessing }
GLMPhlowrTableColumn >> style [
	^ style
]

{ #category : #accessing }
GLMPhlowrTableColumn >> style: anObject [
	style := anObject
]

{ #category : #accessing }
GLMPhlowrTableColumn >> title [
	^ title
]

{ #category : #accessing }
GLMPhlowrTableColumn >> title: anObject [
	title := anObject
]
